### PR TITLE
Small html2htpy fixes

### PR DESCRIPTION
**Pull request by pelme**

### CODE REVIEW

**Comment by pelme** [comment]
hi @OleJoik, what do you think about these changes?

**Comment by OleJoik** [comment]
```
   - shorthand: bool = False if args.no_shorthand else True
   + shorthand = not args.no_shorthand
```

easier to read!

**Comment by OleJoik** [comment]
By the way, I see that I forgot to add a link to the new docs page on the root readme. Maybe could add that in this one also?

**Comment by pelme** [comment]
Good catch, I added it now too! Published 24.6.0 to pypi with these changes. Again thanks a lot for this, looking forward to use this!

**Pull request merged**
