### PR TITLE
build: 🛠 add upper boundary to Markupsafe to avoid breaking changes from unreleased v3

### PR DESCRIPTION
**Pull request by wolfskaempf**
v3.0 of Markupsafe is described as [unreleased and not stable](https://markupsafe.palletsprojects.com/en/latest/changes/), yet it is already on [pypi](https://pypi.org/project/MarkupSafe/#history). To avoid using it prematurely, we need to add this upper boundary.

### CODE REVIEW

**Comment by pelme** [comment]
It seems like 3.0.1 is released but not updated on the docs site: https://github.com/pallets/markupsafe/issues/474

So I think 3.x should be a fine release, will look into why it is failing with htpy!

**Comment by pelme** [comment]
Jinja also uses markupsafe>2.0 so I think people would have a ton of breakages if it was a bad release!

Also: I will switch CI to use 3.13 final now that it is out.

**Comment by pelme** [comment]
Switching to the Python 3.13 release (not release candidate)  causes all tests to pass (see #45).

@wolfskaempf @nip3o can you provide some more details on what is wrong with markupsafe 3.x? All internal htpy tests are passing and they are quite extensive when it comes to checking integration with Django templates and when things are expected to be escaped or not.

**Comment by wolfskaempf** [comment]
Now that it is clear that 3.0.1 is considered stable, the approach should not be to pin the version to `<3`. Therefore I will close this PR and instead open an issue with more details about the breakage after some further investigation.

**Pull request closed without merging**
